apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misskey.fullname" . }}-web
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "misskey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      annotations:
        operator.1password.io/inject: web
      labels:
        {{- include "misskey.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "misskey.fullname" . }}
      containers:
      - name: web
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        command:
        - sh
        - -c
        - 'cat /mnt/config-tpl/default.yml.tpl | envsubst > /misskey/.config/default.yml && cat /mnt/config-tpl/docker.env.tpl | envsubst > /misskey/.config/docker.env && pnpm run migrateandstart'
        ports:
        - name: http
          containerPort: {{ .Values.web.port }}
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
        volumeMounts:
        - name: config-tpl
          mountPath: /mnt
        env:
        - name: OP_SERVICE_ACCOUNT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.onepassword.serviceAccountName }}
              key: token
        - name: URL
          value: {{ .Values.url | quote }}
        - name: PORT
          value: {{ .Values.web.port | quote }}
        - name: DATABASE_HOST
          value: {{ .Values.database.host | quote }}
        - name: DATABASE_PORT
          value: {{ .Values.database.host | quote }}
        - name: DATABASE_DATABASE
          value: {{ .Values.database.database | quote }}
        - name: DATABASE_USER
          value: {{ .Values.database.username | quote }}
        - name: DATABASE_PASS
          value: {{ .Values.database.password | quote }}
        - name: REDIS_HOST
          value: {{ .Values.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.redis.port | quote }}
        - name: REDIS_PASS
          value: {{ .Values.redis.password | quote }}
        - name: MEILISEARCH_HOST
          value: {{ .Values.meilisearch.host | quote }}
        - name: MEILISEARCH_PORT
          value: {{ .Values.meilisearch.port | quote }}
        - name: MEILISEARCH_API_KEY
          value: {{ .Values.meilisearch.apiKey | quote }}
        - name: MEILISEARCH_SSL
          value: {{ .Values.meilisearch.ssl | quote }}
        - name: MEILISEARCH_INDEX
          value: {{ .Values.meilisearch.index | quote }}
      volumes:
      - name: config-tpl
        configMap:
          name: {{ include "misskey.fullname" . }}-config-tpl
          items:
          - key: default.yml.tpl
            path: default.yml.tpl
          - key: docker.env.tpl
            path: docker.env.tpl
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "misskey.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: web
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "misskey.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: web
