apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wireguard
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: wireguard
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
