apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fediq
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: fediq
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
