apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: tavern-house-bookstack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: tavern-house
  destination:
    namespace: tavern-house
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pbzweihander/infra.git
    path: chart/bookstack
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 3
        image:
          tag: 23.10
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          hosts:
          - host: shelf.tavern.house
            paths:
            - path: "/"
              pathType: Prefix
        podAnnotations:
          operator.1password.io/inject: bookstack
        additionalEnvs:
        - name: OP_SERVICE_ACCOUNT_TOKEN
          valueFrom:
            secretKeyRef:
              name: onepassword-service-account
              key: token
        volumes:
        - name: op # required by 1password injector
          emptyDir: {}
        volumeMounts:
        - name: op # required by 1password injector
          mountPath: /var/www/.config/op
        initContainers:
        - name: set-op-dir-ownership # required by 1password injector
          image: busybox
          command:
          - chown
          - -R
          - 33:33
          - /var/www/.config/op
          volumeMounts:
          - name: op
            mountPath: /var/www/.config/op
        command: ["/bin/docker-entrypoint.sh"] # required by 1password injector
        key: op://strike-witches/tavern-house-bookstack-app-key/password
        url: https://shelf.tavern.house
        lang: ko
        database:
          host: op://strike-witches/tavern-house-bookstack-rds/hostname
          port: op://strike-witches/tavern-house-bookstack-rds/port
          database: op://strike-witches/tavern-house-bookstack-rds/database
          username: op://strike-witches/tavern-house-bookstack-rds/username
          password: op://strike-witches/tavern-house-bookstack-rds/password
        mail:
          from: noreply@tavern.house
          fromName: "Elder Scrolls Tavern"
          host: email-smtp.ap-northeast-1.amazonaws.com
          port: 2587
          username: op://strike-witches/tavern-house-ses/username
          password: op://strike-witches/tavern-house-ses/password
        s3:
          key: op://strike-witches/tavern-house-bookstack-r2/username
          secret: op://strike-witches/tavern-house-bookstack-r2/password
          bucket: tavern-house-bookstack
          endpoint: https://4c92705a50dd61764cd79dac00dfcc60.r2.cloudflarestorage.com
          url: https://object.shelf.tavern.house
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
