apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tavern-house
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: tavern-house
      server: https://kubernetes.default.svc
  sourceRepos:
    - "*"
