apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bookstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bookstack.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "bookstack.serviceAccountName" . }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: bookstack
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_KEY
              value: {{ .Values.key | quote }}
            - name: APP_URL
              value: {{ .Values.url | quote }}
            - name: APP_LANG
              value: {{ .Values.lang | quote }}
            - name: DB_HOST
              value: {{ .Values.database.host | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: DB_DATABASE
              value: {{ .Values.database.database | quote }}
            - name: DB_USERNAME
              value: {{ .Values.database.username | quote }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: MAIL_FROM
              value: {{ .Values.mail.from | quote }}
            - name: MAIL_FROM_NAME
              value: {{ .Values.mail.fromName | quote }}
            - name: MAIL_HOST
              value: {{ .Values.mail.host | quote }}
            - name: MAIL_PORT
              value: {{ .Values.mail.port | quote }}
            - name: MAIL_USERNAME
              value: {{ .Values.mail.username | quote }}
            - name: MAIL_PASSWORD
              value: {{ .Values.mail.password | quote }}
            - name: MAIL_ENCRYPTION
              value: {{ .Values.mail.encryption | quote }}
            - name: MAIL_VERIFY_SSL
              value: {{ .Values.mail.verifySsl | quote }}
            - name: CACHE_DRIVER
              value: database
            - name: SESSION_DRIVER
              value: database
            - name: SESSION_SECURE_COOKIE
              value: "true"
            - name: STORAGE_TYPE
              value: s3
            - name: STORAGE_S3_KEY
              value: {{ .Values.s3.key | quote }}
            - name: STORAGE_S3_SECRET
              value: {{ .Values.s3.secret | quote }}
            - name: STORAGE_S3_BUCKET
              value: {{ .Values.s3.bucket | quote }}
            - name: STORAGE_S3_REGION
              value: {{ .Values.s3.region | quote }}
            - name: STORAGE_S3_ENDPOINT
              value: {{ .Values.s3.endpoint | quote }}
            - name: STORAGE_URL
              value: {{ .Values.s3.url | quote }}
            {{- with .Values.additionalEnvs }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
