apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ommrema.fullname" . }}
  labels:
    {{- include "ommrema.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ommrema.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ommrema.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        startupProbe:
          httpGet:
            path: /
            port: http
          failureThreshold: 30
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        envFrom:
        - secretRef:
            name: {{ include "ommrema.fullname" . }}-env
