apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ommrema.fullname" . }}-env
  labels:
    {{- include "ommrema.labels" . | nindent 4 }}
type: Opaque
stringData:
  TITLE: {{ .Values.title | quote }}
  PUBLIC_URL: {{ .Values.url | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | quote }}
  DISCORD_CLIENT_ID: {{ .Values.discord.clientId | quote }}
  DISCORD_CLIENT_SECRET: {{ .Values.discord.clientSecret | quote }}
  DISCORD_GUILD_ID: {{ .Values.discord.guildId | quote }}
  DISCORD_GUILD_ROLE_ID: {{ .Values.discord.guildRoleId | quote }}
  S3_BUCKET_NAME: {{ .Values.s3.bucket | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.s3.region | quote }}
  AWS_ENDPOINT: {{ .Values.s3.endpoint  | quote}} 
