apiVersion: v1
kind: Service
metadata:
  name: {{ include "ommrema.fullname" . }}
  labels:
    {{- include "ommrema.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "ommrema.selectorLabels" . | nindent 4 }}
