apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: aquarium-yuri-garden
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: aquarium-yuri-garden
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
