apiVersion: v1
kind: Service
metadata:
  name: {{ include "mumble.fullname" . }}
  labels:
    {{- include "mumble.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.domain }}
    external-dns.alpha.kubernetes.io/endpoints-type: NodeExternalIP
spec:
  type: NodePort
  ports:
  - port: 64738
    targetPort: mumble-tcp
    protocol: TCP
    name: mumble-tcp
    nodePort: 30738
  - port: 64738
    targetPort: mumble-udp
    protocol: UDP
    name: mumble-udp
    nodePort: 30738
  selector:
    {{- include "mumble.selectorLabels" . | nindent 4 }}
