apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misskey.fullname" . }}-web
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "misskey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "misskey.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /misskey/.config
      volumes:
      - name: config
        secret:
          secretName: {{ include "misskey.fullname" . }}
          items:
          - key: default.yml
            path: default.yml
          - key: docker.env
            path: docker.env
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "misskey.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: web
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "misskey.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: web
