apiVersion: v1
kind: Secret
metadata:
  name: {{ include "misskey.fullname" . }}
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
type: Opaque
stringData:
  default.yml: |
    url: {{ .Values.url | quote }}
    port: 3000
    db:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      db: {{ .Values.database.database }}
      user: {{ .Values.database.username }}
      pass: {{ .Values.database.password }}
      {{- with .Values.database.extras }}
      extra:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.database.replicas }}
    dbReplications: true
    dbSlaves:
    {{- range .Values.database.replicas }}
    - host: {{ .host }}
      port: {{ .port }}
      db: {{ .database }}
      user: {{ .username }}
      pass: {{ .password }}
    {{- end }}
    {{- else }}
    dbReplications: false
    {{- end }}
    redis:
      host: {{ include "misskey.redis.fullname" . }}-master
      port: 6379
      pass: {{ .Values.redis.auth.password }}
    meilisearch:
      host: {{ .Values.meilisearch.fullnameOverride }}
      port: 7700
      apiKey: {{ .Values.meilisearch.environment.MEILI_MASTER_KEY }}
      index: misskey
    id: 'aid'
    proxyBypassHosts:
    - api.deepl.com
    - api-free.deepl.com
    - www.recaptcha.net
    - hcaptcha.com
    - challenges.cloudflare.com
    signToActivityPubGet: true
    proxyRemoteFiles: false
  docker.env: |
    POSTGRES_HOST={{ .Values.database.host }}
    POSTGRES_PORT={{ .Values.database.port }}
    POSTGRES_DB={{ .Values.database.database }}
    POSTGRES_USER={{ .Values.database.username }}
    POSTGRES_PASSWORD={{ .Values.database.password }}
    DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
