apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: yuri-garden-meilisearch
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: yuri-garden
  destination:
    namespace: yuri-garden
    server: https://kubernetes.default.svc
  source:
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    chart: meilisearch
    targetRevision: 0.2.2
    helm:
      values: |
        environment:
          MEILI_ENV: production
          MEILI_MASTER_KEY: "${master_key}"
        persistence:
          enabled: true
          size: 50Gi
          storageClass: gp3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
