apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: yuri-garden-misskey
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: yuri-garden
  destination:
    namespace: yuri-garden
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pbzweihander/infra.git
    path: chart/misskey-op
    targetRevision: HEAD
    helm:
      values: |
        url: https://yuri.garden
        web:
          replicaCount: 3
          image:
            repository: ghcr.io/pbzweihander/misskey
            tag: 2024.8.0-yurigarden.0
          resources:
            requests:
              cpu: 300m
              memory: 1.2Gi
            limits:
              cpu: 300m
              memory: 1.2Gi
          filter:
            resources:
              requests:
                cpu: 100m
                memory: 300Mi
              limits:
                cpu: 100m
                memory: 300Mi
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
            alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          host: yuri.garden
        database:
          host: op://strike-witches/yuri-garden-rds/hostname
          port: op://strike-witches/yuri-garden-rds/port
          database: op://strike-witches/yuri-garden-rds/database
          username: op://strike-witches/yuri-garden-rds/username
          password: op://strike-witches/yuri-garden-rds/password
        redis:
          host: op://strike-witches/yuri-garden-elasticache/hostname
          password: op://strike-witches/yuri-garden-elasticache/password
        meilisearch:
          host: yuri-garden-meilisearch
          port: 7700
          apiKey: op://strike-witches/yuri-garden-meilisearch/password
          index: misskey
        onepassword:
          serviceAccountName: onepassword-service-account
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
