apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: yuri-garden-outline
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: yuri-garden
  destination:
    namespace: yuri-garden
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pbzweihander/infra.git
    path: chart/outline
    targetRevision: HEAD
    helm:
      values: |
        replicaCount: 3
        image:
          tag: 0.72.0-pbzweihander.0
          pullPolicy: Always
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
            alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          hosts:
          - host: outline.yuri.garden
            paths:
            - path: "/"
              pathType: Prefix
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: "${roleArn}"
        outline:
          secretKey: "${outline.secretKey}"
          utilsSecret: "${outline.utilsSecret}"
          url: https://outline.yuri.garden
          defaultLanguage: ko_KR
        database:
          url: "${database.url}"
        redis:
          auth:
            password: "${redis.password}"
        s3:
          region: ap-northeast-1
          uploadBucketUrl: "https://${s3.bucket}.s3.ap-northeast-1.amazonaws.com"
          uploadBucketName: "${s3.bucket}"
          forcePathStyle: "false"
        oidc:
          clientId: "${oidc.clientId}"
          clientSecret: "${oidc.clientSecret}"
          authUri: https://yuri.garden/oauth/authorize
          tokenUri: https://yuri.garden/oauth/token
          userinfoUri: https://yuri.garden/oauth/userinfo
          displayName: 백합.정원
          scopes: read:account
        smtp:
          host: email-smtp.ap-northeast-1.amazonaws.com
          port: 465
          username: "${smtp.username}"
          password: "${smtp.password}"
          fromEmail: 백합정원 <noreply@yuri.garden>
          secure: "true"
        iframely:
          apiKey: "${iframely.apiKey}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

