apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fediq.fullname" . }}
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fediq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fediq.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "fediq.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["fediq"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PUBLIC_URL
              value: {{ .Values.fediq.publicUrl }}
            - name: JWT_SECRET
              value: {{ .Values.fediq.jwtSecret }}
            - name: POSTER_CONTAINER_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: POSTER_SERVICEACCOUNT_NAME
              value: {{ include "fediq.fullname" . }}-poster
            - name: STREAMING_CONTAINER_IMAGE
              value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            - name: STREAMING_SERVICEACCOUNT_NAME
              value: {{ include "fediq.fullname" . }}-streaming
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
