apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fediq.fullname" . }}
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fediq.fullname" . }}
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fediq.fullname" . }}
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "fediq.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fediq.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fediq.fullname" . }}-poster
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
    app.kubernetes.io/component: poster
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fediq.fullname" . }}-poster
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
    app.kubernetes.io/component: poster
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fediq.fullname" . }}-poster
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
    app.kubernetes.io/component: poster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "fediq.fullname" . }}-poster
subjects:
- kind: ServiceAccount
  name: {{ include "fediq.fullname" . }}-poster
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fediq.fullname" . }}-streaming
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fediq.fullname" . }}-streaming
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "fediq.fullname" . }}-streaming
  labels:
    {{- include "fediq.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "fediq.fullname" . }}-streaming
subjects:
- kind: ServiceAccount
  name: {{ include "fediq.fullname" . }}-streaming
