apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: elderscrolls-space-meilisearch
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: elderscrolls-space
  destination:
    namespace: elderscrolls-space
    server: https://kubernetes.default.svc
  source:
    repoURL: https://meilisearch.github.io/meilisearch-kubernetes
    chart: meilisearch
    targetRevision: 0.3.0
    helm:
      values: |
        replicaCount: "0"
        environment:
          MEILI_ENV: production
        auth:
          existingMasterKeySecret: elderscrolls-space-meilisearch-master-key
        persistence:
          enabled: true
          size: 50Gi
          storageClass: gp3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
