apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: elderscrolls-space-misskey
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: elderscrolls-space
  destination:
    namespace: elderscrolls-space
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/pbzweihander/infra.git
    path: chart/misskey-op
    targetRevision: HEAD
    helm:
      values: |
        url: https://elderscrolls.space
        web:
          replicaCount: 0
          image:
            repository: ghcr.io/pbzweihander/misskey
            tag: 2024.2.0-pbzweihander.0
          resources:
            requests:
              cpu: 300m
              memory: 1.2Gi
            limits:
              cpu: 300m
              memory: 1.2Gi
          filter:
            resources:
              requests:
                cpu: 100m
                memory: 300Mi
              limits:
                cpu: 100m
                memory: 300Mi
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
            alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\": 80}, {\"HTTPS\":443}]"
            alb.ingress.kubernetes.io/ssl-redirect: "443"
          hosts:
          - host: elderscrolls.space
            paths:
            - path: "/"
              pathType: Prefix
        database:
          host: op://strike-witches/elderscrolls-space-misskey-rds/hostname
          port: op://strike-witches/elderscrolls-space-misskey-rds/port
          database: op://strike-witches/elderscrolls-space-misskey-rds/database
          username: op://strike-witches/elderscrolls-space-misskey-rds/username
          password: op://strike-witches/elderscrolls-space-misskey-rds/password
        redis:
          host: op://strike-witches/elderscrolls-space-misskey-elasticache/hostname
          password: op://strike-witches/elderscrolls-space-misskey-elasticache/password
        meilisearch:
          host: elderscrolls-space-meilisearch
          port: 7700
          apiKey: op://strike-witches/elderscrolls-space-meilisearch/password
          index: misskey
        onepassword:
          serviceAccountName: onepassword-service-account
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
