apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: elderscrolls-space
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  destinations:
  - namespace: elderscrolls-space
    server: https://kubernetes.default.svc
  sourceRepos:
  - "*"
