apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "misskey.fullname" . }}-web
data:
  default.yml: |
    url: {{ .Values.url }}
    port: {{ .Values.web.port }}
    db:
      host: {{ .Values.database.host }}
      port: {{ .Values.database.port }}
      db: {{ .Values.database.database }}
      user: {{ .Values.database.username }}
      pass: {{ .Values.database.password }}
    dbReplications: false
    redis:
      host: {{ .Values.redis.host }}
      port: {{ .Values.redis.port }}
      pass: {{ .Values.redis.password }}
    meilisearch:
      host: {{ .Values.meilisearch.host }}
      port: {{ .Values.meilisearch.port }}
      apiKey: {{ .Values.meilisearch.apiKey }}
      ssl: {{ .Values.meilisearch.ssl }}
      index: {{ .Values.meilisearch.index }}
    id: 'aid'
    proxyBypassHosts:
    - api.deepl.com
    - api-free.deepl.com
    - www.recaptcha.net
    - hcaptcha.com
    - challenges.cloudflare.com
    signToActivityPubGet: true
  envfile: |
    POSTGRES_USER={{ .Values.database.user }}
    POSTGRES_PASSWORD={{ .Values.database.password }}
    POSTGRES_DB={{ .Values.database.database }}
