apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "misskey.fullname" . }}-web
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "misskey.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "misskey.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      serviceAccountName: {{ include "misskey.fullname" . }}
      containers:
      - name: web
        image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
        imagePullPolicy: {{ .Values.web.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.web.port }}
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources:
          {{- toYaml .Values.web.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /misskey/.config
      volumes:
      - name: config
        configMap:
          name: {{ include "misskey.fullname" . }}-web
          items:
          - key: default.yml
            path: default.yml
          - key: envfile
            path: docker.env
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            {{- include "misskey.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: web
