apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "misskey.fullname" . }}
  labels:
    {{- include "misskey.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
