url: ""

web:
  replicaCount: 1

  image:
    repository: okteto.dev/misskey
    pullPolicy: IfNotPresent
    tag: ""

  port: 3000

  resources: {}

  service:
    type: ClusterIP
    port: 80

  filter:
    image:
      repository: ghcr.io/pbzweihander/spam-musubi
      pullPolicy: Always
      tag: edge

    resources: {}

    service:
      port: 8080

ingress:
  enabled: false
  annotations: {}
  className: ""
  host: ""

serviceAccount:
  annotations: {}

database:
  host: ""
  port: 5432
  database: ""
  username: ""
  password: ""

redis:
  host: ""
  port: 6379
  password: ""

meilisearch:
  host: ""
  port: 7700
  apiKey: ""
  index: ""

onepassword:
  serviceAccountName: ""
